config/routes.rb
Logbook::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :assets do
    resources :asset_versions
  end

  root :to => "admin/dashboard#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :roles, :first_name, :last_name, :nip
  
  has_many :projects
  has_many :projects_i_lead, :foreign_key => :leader_id
  has_many :audits_i_lead, :foreign_key => :leader_id
  has_many :audits_values, :foreign_key => :user_id
  has_many :assets, :foreign_key => :owner_id
  has_many :asset_updaters, :foreign_key => :updated_by_id
  has_many :asset_versions, :foreign_key => :uploader_id
  has_many :document_groups
  has_many :documents
  
  scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0"} }
  
  def name
    first_name.nil? ? email : first_name + ' ' + last_name
  end
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask || 0) & 2**ROLES.index(r)).zero?
    end
  end
  
  def is?(role)
    roles.include?(role.to_s)
  end
  
end

app/views/admin/admin_users/_admin_user_form.html.erb
<%= semantic_form_for [:admin, @admin_user] do |f| %>
  <%= f.inputs "User Info" do %>
    <%= f.input :email%>
    <%= f.input :first_name%>
    <%= f.input :last_name%>
    <%= f.input :nip%>
    <% if can?(:edit, @admin_user)%>
      <% if @admin_user.new_record? %>
        <%= f.input :password%>
        <%= f.input :password_confirmation%>
      <% end %>
      <%=f.input :roles, :collection => ROLES, :as => :check_boxes%>
    <% end %>
  <% end %>
  <%= f.buttons%>
<% end %>

app/views/admin/admin_users/_new_password.html.erb
<%= semantic_form_for [:admin, current_admin_user], :url => update_password_admin_admin_users_path do |f| %>
  <%= f.inputs "New Password" do %>
    <%= f.input :password%>
    <%= f.input :password_confirmation%>
  <% end %>
  <%= f.buttons do%>
    <%= f.commit_button "Change Password"%>
    <%= link_to "Cancel", admin_admin_users_path%>
  <% end %>
<% end %>